---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: unit_tests
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/cop-node:12-alpine
  commands:
  - node -v
  - npm -v
  - npm ci
  - npm run test
  - pwd
  - ls -al
  when:
    event:
    - push

- name: sonarqube_scanner
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/sonar-scanner-node:latest
  when:
    event:
    - push
      
- name: image_to_quay
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cerberus-ui-service
    tags: ${DRONE_COMMIT_SHA}
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_PASSWORD
    DOCKER_USERNAME:
      from_secret: QUAY_USERNAME
  when:
    branch:
    - main
    event:
    - push

- name: test_image_to_quay
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cerberus-ui-service
    dockerfile: cron-Dockerfile
    tags:
      - cron-${DRONE_COMMIT_SHA}
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_PASSWORD
    DOCKER_USERNAME:
      from_secret: QUAY_USERNAME
  when:
    branch:
       - main
    event:
       - push

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

- name: anchore-submission-server
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  commands:
  - /run.sh server

...
