---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.CERBERUS_UI_NAME}}
  labels:
    service: {{.CERBERUS_UI_NAME}}
spec:
  selector:
    matchLabels:
      name: {{.CERBERUS_UI_NAME}}
  replicas: 3
  revisionHistoryLimit: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: {{.CERBERUS_UI_NAME}}
        service: {{.CERBERUS_UI_NAME}}
    spec:
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      containers:
      - name: {{.CERBERUS_UI_NAME}}-proxy
        image: "{{.NGINX_IMAGE}}:{{.NGINX_TAG}}"
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: "{{.CERBERUS_UI_PORT}}"
          - name: SERVER_CERT
            value: "/certs/tls.crt"
          - name: SERVER_KEY
            value: "/certs/tls.key"
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: STATSD_METRICS
            value: "FALSE"
        ports:
          - name: https
            containerPort: 10443
        volumeMounts:
          - name: certs
            mountPath: /certs
      - name: {{.CERBERUS_UI_NAME}}
        image: {{.CERBERUS_UI_IMAGE}}:{{.CERBERUS_UI_TAG}}
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
        command: ["/bin/sh"]
        args: ["-c", "/run.sh"]
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: {{.API_FORM_PORT}}
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 15
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: {{.API_FORM_PORT}}
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 15
        env:
          - name: API_BASE_URL
            value: "{{.API_BASE_URL}}"
          - name: KEYCLOAK_AUTH_URL
            value: "{{.KEYCLOAK_AUTH_URL}}"
          - name: KEYCLOAK_CLIENT_ID
            value: "{{.KEYCLOAK_CLIENT_ID}}"
          - name: KEYCLOAK_REALM
            value: "{{.KEYCLOAK_REALM}}"
          - name: NGINX_CONFIG_FILE
            value: "{{.NGINX_CONFIG_FILE}}"
      volumes:
      - name: certs
        secret:
          secretName: "{{.CERBERUS_UI_NAME}}-pod-cmio"
