---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.CERBERUS_UI_NAME}}
spec:
  podSelector:
    matchLabels:
      name: {{.CERBERUS_UI_NAME}}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-external
    ports:
      - port: 10443
        protocol: TCP
