---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .NAME }}"
type: Opaque
data:
  cypress_cache_folder: "{{.CYPRESS_CACHE_FOLDER | b64enc}}"
  kube_namespace: "{{.KUBE_NAMESPACE | b64enc}}"
  cypress_kc_realm: "{{.CYPRESS_KC_REALM | b64enc}}"
  cypress_kc_root: "{{.CYPRESS_KC_ROOT | b64enc}}"
  cypress_camunda_url: "{{.CYPRESS_CAMUNDA_URL | b64enc}}"
  auth_client: "{{.AUTH_CLIENT | b64enc}}"
  cypress_key: "{{.CYPRESS_KEY | b64enc}}"
  report_base_url: "{{.REPORT_BASE_URL | b64enc}}"
  slack_web_hook: "{{.SLACK_WEB_HOOK | b64enc}}"
  s3_bucket_name: "{{.S3_BUCKET_NAME | b64enc}}"
  s3_access_key: "{{.S3_ACCESS_KEY | b64enc}}"
  s3_secret_key: "{{.S3_SECRET_KEY | b64enc}}"
  auth_realm: "{{.AUTH_REALM | b64enc}}"
  cypress_auth_client_id: "{{.CYPRESS_AUTH_CLIENT_ID | b64enc}}"
  cypress_cerberus_user: "{{.CYPRESS_CERBERUS_USER | b64enc}}"
  cypress_cerberus_password: "{{.CYPRESS_CERBERUS_PASSWORD | b64enc}}"
